### ISSUE TITLE
Making mutualfun.live Live! 

### ISSUE THREAD

**Issue by bdougie** [mutualfun/live#13]
![4](https://user-images.githubusercontent.com/5713670/79140273-918b8000-7d6c-11ea-9f93-93e324e75661.png)

[Link to video](https://www.youtube.com/watch?v=FZoc2zhiaIM&feature=youtu.be)

## Show notes:

10th April, 2020 3pm UTC-7

**Agenda:**

1. Making mutualfun.live work 
2. Link URL to issues on GitHub
3. Embed Twitch and chat

**Reminder:** 

- Star and Watch the [mutualfun/live](https://github.com/MutualFun/live/) repo for updates.

## Relevant links

- [Twitch](https://www.twitch.tv/popout/me8bot/chat)
- [Twitter](https://twitter.com/bdougieyo)
- [MutualFun on GitHub](https://github.com/mutualfun/live)
- [MutualFun site](https://mutualfun.io)
- [Spotify Music playlist](https://open.spotify.com/playlist/7zrrIjhj4DuiVC9D6MRVMZ?si=S0QGUYxZTmC278Qw_jMwZg)
- [Party Corgi Streamer Discord](https://discordapp.com/invite/S9Gdagv)

**Comment by notBdougie** [comment]
.take
