### ISSUE TITLE
zeit/next.js - Open Source Friday

### ISSUE THREAD

**Issue by bdougie** [mutualfun/live#19]
## Show notes:

1st May 9:00 AM UTC-7

**Agenda:**

1. Chat with @timneutkens [zeit/next.js](https://github.com/zeit/next.js)

**Reminder:** 

- Star and Watch the [mutualfun/live](https://github.com/MutualFun/live/) repo for updates.

## Relevant links

- [Twitch](https://www.twitch.tv/popout/bdougieYO/chat)
- [Twitter](https://twitter.com/bdougieyo)
- [MutualFun on GitHub](https://github.com/mutualfun/live)
- [MutualFun site](https://mutualfun.io)
- [Spotify Music playlist](https://open.spotify.com/playlist/7zrrIjhj4DuiVC9D6MRVMZ?si=S0QGUYxZTmC278Qw_jMwZg)
- [Party Corgi Streamer Discord](https://discordapp.com/invite/S9Gdagv)
- [The Live Coders](https://livecoders.dev/)

**Comment by yg** [comment]
I'm so excited to see this chat live on Twitch :purple_heart: 

![](https://media3.giphy.com/media/7eAvzJ0SBBzHy/giphy.gif)

**Comment by bdougie** [comment]
I forgot to update. We ended up pushing this to twitch.tv/github. Hopefully, you were able to see it. All future maintainer chats will be hosted there moving forward, but feel free to join the mutualfun.live streams for live coding. 

https://www.twitch.tv/github/clip/TransparentKitschyNostrilSmoocherZ?filter=clips&range=7d&sort=time

**Comment by yg** [comment]
@bdougie No Problem, I turned on notification for both your's and GitHub's Twitch (cuz I :purple_heart: you guys). I watched the stream live yesterday.
